### ISSUE TITLE
I am looking for a very similar module

### ISSUE THREAD

**Issue by vvo** [catdad/css-raw-loader#1]
Hi, I am trying to use the css-loader and instead of combining it with the style loader, I want to get the output inlined in a variable.

Nowhere have I found how to do so, all examples are always using the style-loader that will add the style content as a stylesheet.

I want to get the css file output inlined (like when using the raw-loader) and then insert the CSS myself using https://github.com/substack/insert-css

Do you know any solution to do so? Thanks.

**Comment by catdad** [comment]
Sounds like what you are looking for is in fact the [`raw-loader`](https://github.com/webpack/raw-loader) itself. Did you try using it?

This is in the docs:

``` javascript
var fileContent = require("raw!./file.txt");
// => returns file.txt content as string
```

**Comment by vvo** [comment]
Yes I tried but it's not working along with css-loader, it seems like https://github.com/gajus/to-string-loader is what would need to be used.

**Comment by catdad** [comment]
Why are you using the CSS loader in the first place? That adds extra stuff to load it into the web page itself. You need to use `raw-loader` **instead of** `css-loader`, not in addition to. Anything meant for CSS will make sure that it is inserted into the web page, because that is the whole purpose of those loaders.

**Comment by vvo** [comment]
I want to benefit from css-loader features (resolves imports..) while still being able to get the generated css content in a variable. css-loader outputs by default an array

**Comment by catdad** [comment]
I'm not really sure how to help then. The `css-raw-loader` is meant to explicitly not allow imports and other such features all while still loading CSS and supporting source maps. It sounds like you actually want the exact opposite of what my module does. Sorry.

**Comment by vvo** [comment]
Solved it, you can use to-string-loader as long with css-loader to get the string output of the css loader in  a variable. Thanks for your time..
